Repository twisted/twisted, pull requests merged in 2024-08, with the labels that each got.

#12275 #12273 Fix twisted.conch tests with OpenSSH >= 9.8
  src/twisted/conch/newsfragments/12273.bugfix
  src/twisted/conch/test/test_cftp.py
  src/twisted/conch/test/test_conch.py
  src/twisted/conch/test/test_ssh.py
Labels: needs-merge

#12278 #12277 Fix usage of hash argument to attr.s
  pyproject.toml
  src/twisted/internet/address.py
  src/twisted/web/_stan.py
  src/twisted/web/newsfragments/12277.bugfix
Labels: needs-merge

#12280 #12279 Fix regression in CopiedFailure
  src/twisted/newsfragments/12279.bugfix
  src/twisted/python/failure.py
  src/twisted/test/test_failure.py
Labels: needs-merge

#12281 #12276 A less flaky test_http11_server_chunked_response
  benchmarks/test_web_server.py
  src/twisted/web/newsfragments/12276.misc
Labels: needs-merge

#12226 12225 Optimize the Deferred await benchmark
  src/twisted/internet/defer.py
  src/twisted/newsfragments/12225.feature
  src/twisted/test/test_defer.py
  src/twisted/web/test/test_flatten.py
Labels: needs-merge

#12232 12230 Stop including the location of where an exception was caught in Failure
  src/twisted/newsfragments/12230.feature
  src/twisted/python/failure.py
  src/twisted/test/test_failure.py
Labels: needs-changes

#12283 12237 add a benchmark for awaiting unfired Defereds, and do some small performance improvements
  benchmarks/test_deferred.py
  src/twisted/internet/defer.py
  src/twisted/newsfragments/12237.feature
Labels: needs-merge

#12285 12284 Speed up chained deferreds slightly
  src/twisted/internet/defer.py
  src/twisted/newsfragments/12284.feature
Labels: needs-merge

#12287 12286 Implement benchmark for callLater() and reactor.runUntilCurrent() and speed them up
  benchmarks/test_calllater.py
  src/twisted/internet/base.py
  src/twisted/newsfragments/12286.feature
Labels: needs-merge

#12291 12290 Fix twisted.internet.test.test_process on Python 313
  .github/workflows/test.yaml
  src/twisted/internet/test/test_process.py
  src/twisted/newsfragments/12290.misc
Labels: needs-merge

#12292 12288 Significantly simplify how Failures work, plus steps towards 3.13 support
  .github/workflows/test.yaml
  src/twisted/internet/defer.py
  src/twisted/internet/test/test_inlinecb.py
  src/twisted/newsfragments/12234.feature
  src/twisted/newsfragments/12288.feature
  src/twisted/python/failure.py
  src/twisted/spread/pb.py
  src/twisted/test/test_failure.py
Labels: needs-merge

#12119 Enable all tests on 3.13 for Linux and macOS
  .github/workflows/test.yaml
  src/twisted/newsfragments/12060.misc
  src/twisted/newsfragments/12062.misc
  src/twisted/newsfragments/12099.misc
Labels: needs-merge

#12236 validate the automat `typical` branch, which adds a type-annotation based interface to Automat
  pyproject.toml
  src/twisted/application/_client_service.py
  src/twisted/application/internet.py
  src/twisted/application/test/test_internet.py
  src/twisted/newsfragments/11236.misc
Labels: needs-merge

#12297 #12296 Report to codecov after combining coverage
  .github/workflows/test.yaml
  codecov.yml
  src/twisted/newsfragments/12296.misc
Labels: needs-review

#12264 #9743 #12191 Faster, more correct HTTP headers
  src/twisted/web/_abnf.py
  src/twisted/web/_http2.py
  src/twisted/web/_newclient.py
  src/twisted/web/client.py
  src/twisted/web/http.py
  src/twisted/web/http_headers.py
  src/twisted/web/newsfragments/12191.feature
  src/twisted/web/newsfragments/9743.misc
  src/twisted/web/server.py
  src/twisted/web/test/test_abnf.py
  src/twisted/web/test/test_http.py
  src/twisted/web/test/test_http_headers.py
  src/twisted/web/test/test_newclient.py
  src/twisted/web/test/test_web.py
Labels: needs-merge
