Repository twisted/twisted, pull requests merged in 2024-06, with the labels that each got.

#12201 12200 - do less attribute lookups on twisted.web.http
  src/twisted/web/newsfragments/12200.misc
  src/twisted/web/server.py
  src/twisted/web/test/test_wsgi.py
Labels: needs-merge

#12199 #12197 - Run benchmarks on Python 3.12 so we can get flamegraphs
  .github/workflows/test.yaml
  src/twisted/newsfragments/12197.misc
Labels: needs-merge

#12198 fix up encoding mess in HTTP log file writing
  src/twisted/newsfragments/12179.misc
  src/twisted/test/test_logfile.py
  src/twisted/web/http.py
  src/twisted/web/test/test_http.py
Labels: needs-merge

#12064 #12063 Deprecation helper function docstring handling consistent with Python 3.13
  src/twisted/newsfragments/12063.removal
  src/twisted/python/deprecate.py
  src/twisted/python/test/test_deprecate.py
Labels: needs-review

#12144 #11893 Move iocp dependency to Windows specific soft dependencies.
  pyproject.toml
  src/twisted/newsfragments/11893.removal
Labels: needs-merge, release-blocker

#12213 12194 Make twisted.web tests pass on Python 3.13
  .github/workflows/test.yaml
  src/twisted/web/_flatten.py
  src/twisted/web/newsfragments/12098.misc
  src/twisted/web/newsfragments/12194.misc
  src/twisted/web/test/test_flatten.py
Labels: needs-merge

#12216 #12215 Use latest coverage version and enable coverage for Python 3.13.
  .github/workflows/test.yaml
  pyproject.toml
  src/twisted/newsfragments/12215.misc
Labels: needs-merge

#12218 12193 Move some of the Twisted infrastructure benchmarks into a codspeed benchmark
  benchmarks/test_deferred.py
  benchmarks/test_linereceiver.py
  src/twisted/newsfragments/12193.misc
Labels: needs-merge

#12224 12223 speed up Deferred.addCallback by removing use of isinstance()
  benchmarks/test_deferred.py
  src/twisted/internet/defer.py
  src/twisted/newsfragments/12223.feature
  src/twisted/test/test_defer.py
Labels: needs-merge
