Repository twisted/twisted, pull requests merged in 2024-01, with the labels that each got.

#12077 fix trunk failing build by pinning PyPy to 3.7.13, as 3.7.14 is failing currently, and add some type annotations to deal with new annotations in pyOpenSSL
  .github/workflows/test.yaml
  src/twisted/internet/_sslverify.py
  src/twisted/internet/iocpreactor/tcp.py
  src/twisted/internet/ssl.py
  src/twisted/internet/tcp.py
  src/twisted/newsfragments/12076.misc
  src/twisted/protocols/amp.py
  src/twisted/python/modules.py
  src/twisted/test/test_amp.py
  src/twisted/trial/_dist/test/test_disttrial.py
  src/twisted/trial/test/test_reporter.py
  src/twisted/web/http.py
Labels: needs-merge

#12079 12078 log regression
  src/twisted/logger/_format.py
  src/twisted/logger/test/test_format.py
  src/twisted/newsfragments/12078.misc
Labels: needs-merge

#12083 12084 PyPy stack depth check change for 7.3.14
  .github/workflows/test.yaml
  src/twisted/internet/defer.py
  src/twisted/newsfragments/12084.bugfix
Labels: needs-merge, release-blocker

#12088 12087 epytext tls transport
  src/twisted/newsfragments/12087.misc
  src/twisted/protocols/tls.py
Labels: needs-merge

#12069 #12068: Fix incorrect env handling in spawnProcess on Posix when posix_spawnp is used.
  src/twisted/internet/process.py
  src/twisted/internet/test/test_process.py
  src/twisted/newsfragments/12068.bugfix
Labels: needs-merge, release-blocker

#12095 #12095 Increase RSA keys generated in tests
  src/twisted/conch/test/test_keys.py
  src/twisted/conch/test/test_manhole_tap.py
  src/twisted/newsfragments/12095.misc
Labels: needs-merge

#11998 #11997 Fix for Twisted web client support of trailer Server-Timing
  src/twisted/newsfragments/11997.bugfix
  src/twisted/web/http.py
  src/twisted/web/test/test_http.py
Labels: needs-review, release-blocker

#12090 #12011 Speed up small TLS writes
  src/twisted/newsfragments/12011.bugfix
  src/twisted/protocols/test/test_tls.py
  src/twisted/protocols/tls.py
Labels: needs-merge
